# Generated by Django 3.1.1 on 2020-09-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamchamp_back', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='favorited',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='streamchamp_back.Stream'),
        ),
    ]
