# Generated by Django 3.1.1 on 2020-09-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamchamp_back', '0002_auto_20200908_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(default=[], to='streamchamp_back.Stream'),
        ),
    ]
