# Generated by Django 3.1.1 on 2020-09-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamchamp_back', '0003_auto_20200909_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='streamchamp_back.Stream'),
        ),
    ]
