# Generated by Django 3.1.1 on 2020-09-11 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamchamp_back', '0008_auto_20200910_2310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
